## Name or list of names in case you want to create several apps with the same configuration
names: hadoop_sample
app_type: hadoop_app

## Resource configuration to load into State Database
cpu_max: 400
cpu_min: 200
mem_max: 4096
mem_min: 2048
cpu_boundary: 10
cpu_boundary_type: "percentage_of_max"
mem_boundary: 1
mem_boundary_type: "percentage_of_max"

## Only used if disk_scaling set to yes
disk_max: 200
disk_min: 100
disk_boundary: 10
disk_boundary_type: "percentage_of_max"

## Only used if power_budgeting set to yes
energy_max: 50
energy_min: 10
energy_boundary: 5
energy_boundary_type: "percentage_of_max"

## The indicated files should be in the same directory as this configuration file
start_script: start.sh
stop_script: stop.sh
app_jar: app_jar.jar
