
- name: Copy apptainer containers cgroup config
  template:
    src: "templates/{{ cgroups_file }}"
    dest: "{{ installation_path }}/{{ cgroups_file }}"

### Fix to add controllers to cgroups V2
- name: Start dummy container
  shell: "{{ singularity_command_alias }} instance start -C --apply-cgroups {{ cgroups_file }} {{ image_file }} dummy_cont"
  args:
    chdir: "{{ installation_path }}"
    executable: /bin/bash

- name: Stop dummy container
  shell: "{{ singularity_command_alias }} instance stop dummy_cont"
  args:
    executable: /bin/bash

- name: get the user id running the deploy
  shell: "echo $UID"
  args:
    executable: /bin/bash
  register: userid_on_the_host

- name: Add controllers to cgroups
  become: yes
  shell: "echo '+{{ item[0] }}' >> {{ item[1] }}/cgroup.subtree_control"
  args:
    chdir: "/sys/fs/cgroup/"
    executable: /bin/bash
  with_nested:
    - [ 'cpu', 'cpuset', 'memory' ]
    - [ 'user.slice', "user.slice/user-{{ userid_on_the_host.stdout }}.slice", "user.slice/user-{{ userid_on_the_host.stdout }}.slice/user@{{ userid_on_the_host.stdout }}.service", "user.slice/user-{{ userid_on_the_host.stdout }}.slice/user@{{ userid_on_the_host.stdout }}.service/user.slice" ]

 ####
- name: Check containers status
  shell: "{{ singularity_command_alias }} instance list -j"
  register: apptainer_list_output
  args:
    executable: /bin/bash

- name: Start apptainer containers
  shell: "{{ singularity_command_alias }} instance start -C --hostname {{ item }} --apply-cgroups {{ cgroups_file }} {{ image_file }} {{ item }}"
  when: "'\"instance\": \"{{ item }}\",' not in apptainer_list_output.stdout"
  args:
    chdir: "{{ installation_path }}"
    executable: /bin/bash
  with_items: "{{ containers }}"