- name: get the username running the deploy
  become: no
  local_action: command whoami
  register: username_on_the_host

- name: Create HWPC Sensor installation directory
  file:
    path: "{{ hwpc_sensor_path }}/image"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"

- name: Create HWPC Sensor configuration directory
  file:
    path: "{{ hwpc_sensor_path }}/config"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"

- name: Create HWPC Sensor reporting directory
  file:
    path: "{{ hwpc_sensor_reporting_path }}"
    state: directory
    owner: "{{ username_on_the_host.stdout_lines[0] }}"