# Stop containers from nodes
- hosts: nodes
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  tasks:
  - name: Stop apptainer containers from nodes
    shell: "sudo {{ singularity_command_alias }} instance stop --all"
    when: "container_engine == 'apptainer'"
    args:
      executable: /bin/bash
    tags: stop_containers_nodes

# Stop containers from server
- hosts: localhost
  gather_facts: no

  vars_files:
    - vars/main.yml
    - config/config.yml

  tasks:
  - name: Stop apptainer containers from server
    shell: "{{ singularity_command_alias }} instance stop --all"
    when: "container_engine == 'apptainer'"
    args:
      executable: /bin/bash
    tags: stop_containers_server